#cloud-config

ssh_authorized_keys:
 - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7k/D+GEVoslqNBTVgilMpxlIYgkR8xUdg39B8QyetvAXqQBVGCvypxOhXhvcH1G5z06aDF1XczOeKfyiqE7xETs8ZwEvxR9+a5VpV1JfEzXSh6/e4ThE8ii0kQsyVH/My6gl9r5AZ0qbw4qKRInweJdNaGvnZLlqCzXMfW+YGTjGdTY7b3bpXwdWBex+6ghw+21pDdrnEJpUiqihSIAMJaR5DD+OBGkKh7INhAiy3Vzgmt79HByUgj9Gu/W1eBW2cRoq7VwjMIVUTXuBIDQ6tP8nqol2/0ERh7PZTPytCjMUzLryNGbmbBg8M/hT7GxSjMpAAhyEeUrxBpJaQ1zCr hscrystal@Linux

hostname: rancheros-01

rancher:
  network:
    dns:
      nameservers:
      - 8.8.8.8
      - 8.8.4.4
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 192.168.0.105/24
        gateway: 192.168.0.253
        mtu: 1500
