version: "2"

services:
  web:
     image: httpd
     environment:
       - "constraint:node==/node[0-9]+/"
     ports:
       - 80
     networks:
       - front

networks:
     front:
       external:
         name: network1
