#cloud-config

hostname: "PieSoft01"

coreos:
    units:
      - name: "docker.service"
        command: start
      - name: "00-eth0.network"
        runtime: true
        content: |
          [Match]
           Name=eth0

          [Network]
          DNS=8.8.8.8
          Address=192.168.0.107/24
          Gateway=192.168.0.253

users:
  - name: "pie"
    passwd: "$1$JWxd62xh$LYNYp3hsD/s8X5a73m2ha/"
    groups:
        - sudo
        - docker
    ssh-authorized-keys:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7k/D+GEVoslqNBTVgilMpxlIYgkR8xUdg39B8QyetvAXqQBVGCvypxOhXhvcH1G5z06aDF1XczOeKfyiqE7xETs8ZwEvxR9+a5VpV1JfEzXSh6/e4ThE8ii0kQsyVH/My6gl9r5AZ0qbw4qKRInweJdNaGvnZLlqCzXMfW+YGTjGdTY7b3bpXwdWBex+6ghw+21pDdrnEJpUiqihSIAMJaR5DD+OBGkKh7INhAiy3Vzgmt79HByUgj9Gu/W1eBW2cRoq7VwjMIVUTXuBIDQ6tP8nqol2/0ERh7PZTPytCjMUzLryNGbmbBg8M/hT7GxSjMpAAhyEeUrxBpJaQ1zCr hscrystal@Linux"
